### ISSUE TITLE
Project name in manifest

### ISSUE THREAD

**Issue by Rookfighter** [build2-packaging/ZeroMQ-libzmq#1]
Hi @boris-kolpackov

I got this build2 package [libzmq](https://github.com/build2-packaging/libzmq) and [cppzmq](https://github.com/build2-packaging/cppzmq), which both belong to the [ZeroMQ](https://zeromq.org/) project. I know that the general guideline is that the project name of a package should be chosen as its git repository name. That would essentially mean that `libzmq` and `cppzmq`would live in separate projects, which feels counter-intuitive to me.

So just wanted to clarify what your opinion on this is.

Personally I would prefer to use the project name `ZeroMQ`, so the packages will also be grouped together on cppget (would just feel more natural to me). Note that there is also a high level C-binding library of ZeroMQ which is also maintained by the project authors (I have no plans of packaging it, though).

**Comment by boris-kolpackov** [comment]
> I got this build2 package [libzmq](https://github.com/build2-packaging/libzmq) and [cppzmq](https://github.com/build2-packaging/cppzmq), which both belong to the [ZeroMQ](https://zeromq.org/) project.

I presume you put them into separate `git` repositories because they are independently-versioned, correct?

> That would essentially mean that `libzmq` and `cppzmq` would live in separate projects, which feels counter-intuitive to me.

Yes, I agree. I think I would do the following:

1. Rename the repositories (but not the packages inside) to `zeromq-libzmq` and `zeromq-cppzmq` (or `ZeroMQ-` if you prefer). I see `cppzmq` is already multi-package but `libzmq` would need to be changed to multi-package for such a rename.

2. Use `project: zeromq` (or `project: ZeroMQ`) in both.

What do you think?

**Comment by Rookfighter** [comment]
> I presume you put them into separate git repositories because they are independently-versioned, correct?

Correct, the libraries are independently versioned and live in separate upstream repos.

> Yes, I agree. I think I would do the following: [...]
> 
> What do you think?

Agree, I will rename the repos. Just note that both repos are already multi-package repos. The difference is just that the `libzmq` repo only contains a single package (as tests and examples do not require any additional dependencies). Or do you mean I should factor the `libzmq` tests out into a separate package, although the tests do not need any additional dependencies?

**Comment by boris-kolpackov** [comment]
> Just note that both repos are already multi-package repos.

Yes, you are right, somewhy I thought it was not when I looked.

> Or do you mean I should factor the libzmq tests out into a separate package, although the tests do not need any additional dependencies?

No, we don't need to do it. The reason it has to be a multi-package repository (with one package) in this case is because the repository and package having different names.

**Comment by Rookfighter** [comment]
Alright, thanks! I renamed the repos.
