### ISSUE TITLE
Difference in ci.stage.build2 and queue.stage.build2

### ISSUE THREAD

**Issue by Rookfighter** [build2-packaging/ZeroMQ-libzmq#2]
Hi @boris-kolpackov 

I was just wondering why the build results for this library look so different in `ci.stage.build2` and `queue.stage.build2`. 

CI: https://ci.stage.build2.org/@219b22c6-254a-46d5-9923-885aa06cec9d
Queue: https://queue.stage.build2.org/libzmq/4.3.4

(both of course with same commit ID)

While CI has only 39 failed builds out of 96 total builds and even 3 successes without warning, Queue does not seem to have a single non-failed build. Do the builds for the two systems work differently? I assumed that queue just runs the same build as in CI.

**Comment by boris-kolpackov** [comment]
I picked one of the successful configurations to investigate (`linux_debian_11-gcc_10.2-bindist`). The failed build has this diagnostics:

```
# step id: bpkg.install 2023-06-20 16:07:02 UTC
bpkg -v install libzmq
b -v install('./libzmq-4.3.4/')
error: no explicit target for libzmq-4.3.4/:dir{tmpBFjMFf/}
  info: while applying rule install.alias to update (for install) dir{libzmq-4.3.4/}
info: failed to update (for install) dir{libzmq-4.3.4/}
```

I then downloaded the archive and confirmed there is no `tmpBFjMFf/`. Then I got the hunch that it is probably created by the test. I then built and tested the library from archive on my machine and sure enough `tmpYxPKdn/` appeared in the root of the source directory. If I then try to install, this directory is picked up by the wildcard and things end up with the same diagnostics as on queue. My guess is that some of the tests you run create the temporary directory in `CWD` (if you cannot change this behavior, you can always try to change the `CWD`, see the `env` builtin for details).

As to why this doesn't reproduce on CI, I believe it should since we also build from source directory on CI. Perhaps the creation (or cleanup) of this directory is flaky?

**Comment by boris-kolpackov** [comment]
> As to why this doesn't reproduce on CI, I believe it should since we also build from source directory on CI. Perhaps the creation (or cleanup) of this directory is flaky?

Ok, that was not quite correct: CI from git builds the package out-of-source, unlike from archive. We probably need to get rid of this difference somehow: https://github.com/build2/build2/issues/285

**Comment by Rookfighter** [comment]
Alright, thanks for investigating and reproducing the issue! Makes sense that it picks up the temporary directory. I will give changing CWD a try, though I will need something that works across the different platforms

**Comment by boris-kolpackov** [comment]
> I will give changing CWD a try, though I will need something that works across the different platforms

`env` is a builtin so it works across all the platforms: https://build2.org/build2/doc/build2-testscript-manual.xhtml#builtins-env

**Comment by boris-kolpackov** [comment]
Ok, I took a stab at this and it was simpler to just wrap it with `testscript`. The commit is here (I've referenced the wrong issue in the commit message): https://github.com/build2-packaging/ZeroMQ-libzmq/commit/e336a9691bb069aa8c50274fb2b921b7bec96f1d

I am going to take the liberty of releasing a revision with this fix since that's the only thing that's blocking migration to cppget.org.

**Comment by Rookfighter** [comment]
Thanks, I merged your test_env branch to main :+1:

**Comment by boris-kolpackov** [comment]
> Thanks, I merged your test_env branch to main

Uh, I've actually done that and even released `4.3.4+1` but I forgot to push my changes. Sorry about that.

The `4.3.4+1` package is sitting in `testing` so I think when you publish yours (hopefully it will work), I will just replace mine with yours since it is a superset of changes.

**Comment by boris-kolpackov** [comment]
> hopefully it will work

Ok, I see it didn't ("duplicate submission"). I've dropped the package from testing, please try to publish again.

**Comment by boris-kolpackov** [comment]
Ok, I moved `4.3.4+2` to `testing`.

BTW, you seem to have broken something in `test-installed` with that `libsodium` change.

**Comment by Rookfighter** [comment]
@boris-kolpackov 
Regarding this:

> BTW, you seem to have broken something in test-installed with that libsodium change.

If I look at the failed run of https://ci.cppget.org/@89e5444b-efb0-404d-8dfe-5884a4892740/libzmq/4.3.4+2/log/aarch64-linux-gnu/linux_debian_12-clang_16_libc%2B%2B-static_O3/default/public/0.16.0/test-installed, I can see these error messages:

```
/tmp/build-installed/tests/src/test_sodium
/tmp/dist/libzmq-4.3.4+2/tests/src/tests/test_sodium.cpp:53:test__zmq_curve_keypair__always__success:FAIL: Expected -1 Was 0
/tmp/dist/libzmq-4.3.4+2/tests/src/tests/test_sodium.cpp:72:test__zmq_curve_public__valid__success:FAIL: Expected -1 Was 0
/tmp/dist/libzmq-4.3.4+2/tests/src/tests/test_sodium.cpp:89:test__zmq_curve_public__invalid__failure_short:FAIL: Expected 95 Was 22
/tmp/dist/libzmq-4.3.4+2/tests/src/tests/test_sodium.cpp:89:test__zmq_curve_public__invalid__failure_long:FAIL: Expected 95 Was 22
```

If I check the mentioned lines, e.g. `test_sodium.cpp:53`, then I see

```
50 #if defined(ZMQ_HAVE_CURVE)
51     TEST_ASSERT_SUCCESS_ERRNO (rc);
52 #else
53     TEST_ASSERT_FAILURE_ERRNO (ENOTSUP, rc);
54 #endif
```

So I checked the build arguments of `test_sodium.cpp`
```
clang++-16 -I/tmp/build-installed/tests/src/external/unity/ -I/tmp/dist/libzmq-4.3.4+2/tests/src/external/unity/ -DUNITY_USE_COMMAND_LINE_ARGS -DUNITY_EXCLUDE_FLOAT -I/opt/private/include -DZMQ_STATIC -I/opt/private/include -DZMQ_STATIC -Wall -O3 -std=c++2b -stdlib=libc++ -Wno-unqualified-std-cast-call -finput-charset=UTF-8 -o build-installed/tests/src/tests/test_sodium.o -c -x c++ /tmp/dist/libzmq-4.3.4+2/tests/src/tests/test_sodium.cpp
```

Which indeed is missing any `poptions` which should get distributed by `lib{zmq_test}`. Any idea why that is not the case here?
Note that the poptions get distributed in my local setup as expected and the tests also succeed.

```
g++ -I/home/fabian/develop/ZeroMQ-libzmq-cc/libzmq/tests/src/external/unity/ -I/home/fabian/develop/ZeroMQ-libzmq/libzmq/tests/src/external/unity/ -DUNITY_USE_COMMAND_LINE_ARGS -DUNITY_EXCLUDE_FLOAT -I/home/fabian/develop/ZeroMQ-libzmq-cc/libzmq/include -I/home/fabian/develop/ZeroMQ-libzmq/libzmq/include -I/home/fabian/develop/ZeroMQ-libzmq-cc/libzmq/src -I/home/fabian/develop/ZeroMQ-libzmq/libzmq/src -DZMQ_USE_CV_IMPL_STL11 -DZMQ_HAVE_NOEXCEPT -DZMQ_CACHELINE_SIZE=64 -DHAVE_FORK -DHAVE_CLOCK_GETTIME -DHAVE_MKDTEMP -DZMQ_HAVE_UIO -DZMQ_HAVE_EVENTFD -DZMQ_HAVE_EVENTFD_CLOEXEC -DZMQ_HAVE_IFADDRS -DZMQ_HAVE_SO_BINDTODEVICE -DZMQ_HAVE_SO_PEERCRED -DZMQ_HAVE_O_CLOEXEC -DZMQ_HAVE_SOCK_CLOEXEC -DZMQ_HAVE_SO_KEEPALIVE -DZMQ_HAVE_SO_PRIORITY -DZMQ_HAVE_TCP_KEEPCNT -DZMQ_HAVE_TCP_KEEPIDLE -DZMQ_HAVE_TCP_KEEPINTVL -DZMQ_HAVE_TCP_KEEPALIVE -DZMQ_HAVE_PTHREAD_SET_AFFINITY -DHAVE_ACCEPT4 -DHAVE_STRNLEN -DZMQ_HAVE_IPC -DZMQ_HAVE_TIPC -DZMQ_USE_BUILTIN_SHA1 -DZMQ_HAVE_WS -DZMQ_HAVE_CURVE -DZMQ_USE_TWEETNACL -DZMQ_HAVE_PTHREAD_SETNAME_2 -DZMQ_IOTHREAD_POLLER_USE_SELECT -DZMQ_POLL_BASED_ON_SELECT -I/home/fabian/develop/ZeroMQ-libzmq-cc/libzmq/include -I/home/fabian/develop/ZeroMQ-libzmq/libzmq/include -std=c++23 -finput-charset=UTF-8 -x c++ -MQ ^ -MD -E -fdirectives-only -MF /home/fabian/develop/ZeroMQ-libzmq-cc/libzmq/tests/src/tests/test_sodium.o.t -o /home/fabian/develop/ZeroMQ-libzmq-cc/libzmq/tests/src/tests/test_sodium.o.ii /home/fabian/develop/ZeroMQ-libzmq/libzmq/tests/src/tests/test_sodium.cpp
```

**Comment by boris-kolpackov** [comment]
@Rookfighter 

I believe that's because `lib{zmq_test}` never gets installed (while its a binless library, it still has `pkg-config` files, which is where all the `poptions` get passed). You need something like this in your `libzmq/src/buildfile`:

```
./: lib{zmq zmq_test}
```

**Comment by Rookfighter** [comment]
Thanks, I finally got to release another revision which fixes this issue. Sorry for the long delay. I'll close this issue since the discussion went "off-topic" anyway, and the actual issue was resolved by your changes.
